### ISSUE TITLE
[Feature] Graphics API Extension

### ISSUE THREAD

**Issue by Nathan-MV** [Admenri/rguplayer#8]
# Properties

- [x] **Graphics.fullscreen**  
   - Check if it is in fullscreen with `Graphics.fullscreen` and toggle it to `true` or `false` with `Graphics.fullscreen=`.
   
- [x] **Graphics.scale**  
   - Scaling feature allowing users to adjust the game window/screen size dynamically with `Graphics.scale=` such as scaling it by 2x or 0.5x.

- [x] **Graphics.vsync**  
   - Toogle it to `true` or `false` with `Graphics.vsync=`.

# Methods

- [x] **Graphics.capture_screen**  
   - Capture in-game screenshots, enabling sharing of memorable moments or troubleshooting assistance through visual representation.

- [x] **Graphics.delta_time**  
   - `Graphics.delta_time` is exceptionally useful for modifying your game to stop synchronizing with the frame rate, ensuring consistent gameplay regardless of variations in frame rate.

- [x] **Graphics.shader**
   - Applying global shaders that will affect all Viewports/Sprites such as xBRZ, scalefx, GameBoy Color...

**Comment by Admenri** [comment]
① Graphics.fullscreen attribute has been added.
② Graphics.resize_window can support the function of Graphics.scale
③ It has added Bitmap.save_png and Viewport.snap_to_bitmap for Graphics.capture_screen
④ Graphics.delta_time: I believe that Graphics.delta_time can be entirely replaced with the built-in Time.now.
⑤ Graphics.shader: Due to the heavy optimization burden carried by Sprite, it's inconvenient to add shader functionality to it. I've only added shader capabilities to geometry and viewport. I believe the functionalities of these two classes should be sufficient to support the effects you mentioned.
